### ISSUE TITLE
Script not working on Ubuntu 16.04 Linux.

### ISSUE THREAD

**Issue by akhan4u** [ibraAbuKaff/answer#1]
Hi, 

I see that the script is not working on my Ubuntu Linux 16.04 VM, with Python 2.7.12 base environment. when i run the script in debug mode, It is able to identify the OS type but showing this usage help of python web-browser module. 

root@puppet: /data/answer # bash -x answer.sh "service oriented architecture"
+ OPERATING_SYS=
+ case "$OSTYPE" in
+ OPERATING_SYS=Linux
+ SEARCH_QUERY='service oriented architecture'
+ GOOGLE_SEARCH='http://www.google.com/search?q=service oriented architecture'
+ STACKOVERFLOW_SEARCH='https://stackoverflow.com/search?q=service oriented architecture'
+ MEDIUM_SEARCH='https://medium.com/search?q=service oriented architecture'
+ REDDIT_SEARCH='https://www.reddit.com/r/programming/search?q=service oriented architecture'
+ YOUTUBE_SEARCH='https://www.youtube.com/results?search_query=service oriented architecture'
+ BING_SAEARCH='https://www.bing.com/search?q=service oriented architecture'
+ WIKIPEDIA_SEARCH='https://en.wikipedia.org/w/index.php?search=service oriented architecture'
+ [[ Linux == \M\a\c\ \O\S ]]
+ [[ Linux == \L\i\n\u\x ]]
+ python -mwebbrowser 'http://www.google.com/search?q=service oriented architecture' 'https://stackoverflow.com/search?q=service oriented architecture' 'https://medium.com/search?q=service oriented architecture' 'https://www.reddit.com/r/programming/search?q=service oriented architecture' 'https://www.bing.com/search?q=service oriented architecture' 'https://en.wikipedia.org/w/index.php?search=service oriented architecture'
Usage: /usr/lib/python2.7/webbrowser.py [-n | -t] url
    -n: open new window
    -t: open new tab
+ [[ Linux == \W\i\n\d\o\w\s ]]

**Comment by ibraAbuKaff** [comment]
The issue has been fixed, in case you get it any more issues, please don't hesitate to raise  : )
